[package]
name = "audio-engine"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
audio-engine-core = { path = "../audio-engine-core", features = ["napi"] }
napi = { version = "3.12.1", features = ["napi9", "serde-json", "tokio_rt"] }
napi-derive = "3.6.3"
ffmpeg_audio = { version = "0.3.1", default-features = false, features = [
  "http",
  "tracing",
] }
parking_lot = "0.12"
anyhow = "1"
tracing = "0.1"
tokio = { version = "1", features = ["rt"] }

[build-dependencies]
napi-build = "2.4.1"

[lints]
workspace = true
